[package]
name = "vsp-router"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
camino = "1"
clap = { version = "3", features = ["derive"] }
nix = { version = "0.25", features = ["term"], default-features = false }
thiserror = "1"
